import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/ui/Topbar/topbar";
import localFont from "next/font/local";

const uncut_sans = localFont({ src: "../fonts/uncut-sans.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${uncut_sans.className} max-w-7xl mx-auto`}>
        <Topbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
